@echo off
echo           - Renaming %COMPUTERNAME% to %1...
netdom renamecomputer localhost /newname:%1 /REboot:3 /Force > NUL
echo           - Restarting to ensure rename has taken effect...
@echo on